[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#6A0DAD"
backgroundColor = "#F3F0F9"
secondaryBackgroundColor = "#FFFFFF" 
textColor = "#2E1A47"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
